org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# JEI
modName=Better Advancements
modFileName=BetterAdvancements
modId=betteradvancements
modAuthor=way2muchnoise
modGroup=betteradvancements
# Mojang ships Java 25 to end users in 26.1+
modJavaVersion=25
githubUrl=way2muchnoise/BetterAdvancements

# Architecutury
platforms=fabric,forge,neoforge

# Minecraft
minecraftVersion=26.2
minecraftVersionRange=[26.2, 26.3)

# Forge
forgeVersion=65.0.9
loaderVersionRange=[65,)
forgeVersionRange=[65.0.0,)

# Fabric
fabricVersion=0.155.2+26.2
fabricLoaderVersion=0.19.3

# NeoForge
neoforgeVersion=26.2.0.28-beta
neoforgeLoaderVersionRange=[4,)
neoforgeVersionRange=[26.2.0,)

# Fabric Config screen
clothVersion=26.2.155
modMenuVersion=20.0.1

# Mappings
mappingsChannel=parchment
mappingsParchmentMinecraftVersion=1.21.11
mappingsParchmentVersion=2025.12.20

# Publishing
curseProjectId=272515
curseHomepageLink=https://www.curseforge.com/minecraft/mc-mods/better-advancements
modrinthProjectId=Q2OqKxDG

# Version
specificationVersion=0.6.0
